### ISSUE TITLE
Q: Does Visual Studio 20XX do the specialization (2017 seems not to?)

### ISSUE THREAD

**Issue by m-7761** [TheWisp/ImpossiblyFastEventCPP17#1]
I hope this isn't annoying, did you try Visual Studio? 2017 doesn't compile the specialization in my code, it says "`example<pointer-to-member> is undefined`" so I'm wondering if this is just a case of Microsoft leaving something unimplemented when moving onto the next VS version. Maybe someone finds this helpful, but for me personally I'm wondering if I'm downloading a new VS tomorrow or if I have to switch to `decltype` or something else. Thanks!

```
template<auto U>
struct example;
template<class S, class T, S T::* U>
struct example<U>{ typedef S first; typedef T second; };
```

**Comment by TheWisp** [comment]
this is a PoC library and unmaintained - maybe check https://github.com/TheWisp/signals if you are interested

**Comment by mick-p1982** [comment]
Hmm, okay. But you do have experience building with Visual Studio? Since I can't download anything until midnight this morning I changed it to a two layer template to make VS2017 work, basically wrapping a type based template with an auto/decltype template. I won't be surprised if VS2019 works but it ends Windows XP support.

(Piece of crap? I assumed it's a demo or something.)

P.S. Do you think signals/slot is a good pattern? I ripped Qt out of app's UI last year, it was very bloated and completely unstructured, so there's no way to tell what anything is doing working with them. With my bad memory I'd forget how my own code worked :)
